// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TamoJunto.Domain.Models;

#nullable disable

namespace TamoJunto.Domain.Migrations
{
    [DbContext(typeof(TamoJuntoContext))]
    [Migration("20250909024659_AdicionarCamposRecuperacaoSenha")]
    partial class AdicionarCamposRecuperacaoSenha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TamoJunto.Domain.Models.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataCompra");

                    b.Property<DateTime>("DataRenovacao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataRenovacao");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCliente");

                    b.Property<Guid?>("IdPagamento")
                        .HasColumnType("uuid")
                        .HasColumnName("IdPagamento");

                    b.Property<Guid?>("IdParceiro")
                        .HasColumnType("uuid")
                        .HasColumnName("IdParceiro");

                    b.Property<Guid>("IdPlano")
                        .HasColumnType("uuid")
                        .HasColumnName("idPlano");

                    b.HasKey("Id")
                        .HasName("pK_Assinatura");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("iX_Assinatura_IdCliente");

                    b.HasIndex("IdPagamento")
                        .IsUnique()
                        .HasDatabaseName("iX_Assinatura_IdPagamento");

                    b.HasIndex("IdPlano")
                        .HasDatabaseName("iX_Assinatura_idPlano");

                    b.ToTable("Assinatura", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Backoffice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("Cpf");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id")
                        .HasName("pK_Backoffice");

                    b.HasIndex(new[] { "Id" }, "IdParceiro_Backoffice_Unique")
                        .HasDatabaseName("iX_Backoffice_id");

                    b.HasIndex(new[] { "IdUsuario" }, "IdUsuario_Backoffice_Unique")
                        .IsUnique()
                        .HasDatabaseName("iX_Backoffice_idUsuario");

                    b.ToTable("Backoffice", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Cpf");

                    b.Property<Guid?>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("IdEmpresa");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id")
                        .HasName("pK_Cliente");

                    b.HasIndex(new[] { "IdEmpresa" }, "IdEmpresa_Cliente_Unique")
                        .IsUnique()
                        .HasDatabaseName("iX_Cliente_idEmpresa");

                    b.HasIndex(new[] { "IdUsuario" }, "IdUsuario_Cliente_Unique")
                        .IsUnique()
                        .HasDatabaseName("iX_Cliente_idUsuario");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.CupomCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataResgate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataResgate");

                    b.Property<DateTime?>("DataUtilizacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DataUtilizacao");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCliente");

                    b.Property<Guid>("IdOfertaParceiro")
                        .HasColumnType("uuid")
                        .HasColumnName("IdOfertaParceiro");

                    b.HasKey("Id")
                        .HasName("pK_CupomCliente");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("iX_CupomCliente_IdCliente");

                    b.HasIndex(new[] { "IdOfertaParceiro" }, "IdOfertaParceiro_CupomCliente_unique")
                        .IsUnique()
                        .HasDatabaseName("iX_CupomCliente_idOfertaParceiro");

                    b.ToTable("CupomCliente", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Atividade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Atividade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nome");

                    b.HasKey("Id")
                        .HasName("pK_Empresa");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Estado");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nome");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("Numero");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Pais");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Rua");

                    b.HasKey("Id")
                        .HasName("pK_Endereco");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("iX_Endereco_IdUsuario");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.HistoricoCupom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataUso")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataUso");

                    b.Property<Guid>("IdCupom")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCupom");

                    b.Property<Guid>("IdCupomClienteNavigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("idCupomClienteNavigationId");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.Property<Guid>("IdUsuarioNavigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("idUsuarioNavigationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("pK_HistoricoCupom");

                    b.HasIndex("IdCupomClienteNavigationId")
                        .HasDatabaseName("iX_HistoricoCupom_idCupomClienteNavigationId");

                    b.HasIndex("IdUsuarioNavigationId")
                        .HasDatabaseName("iX_HistoricoCupom_idUsuarioNavigationId");

                    b.ToTable("HistoricoCupom", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.HistoricoLogin", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("Date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ip");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Local");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("iX_HistoricoLogin_IdUsuario");

                    b.ToTable("HistoricoLogin", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Imagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("IdOfertaParceiro")
                        .HasColumnType("uuid")
                        .HasColumnName("IdOfertaParceiro");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Path");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id")
                        .HasName("pK_Imagem");

                    b.HasIndex("IdOfertaParceiro")
                        .HasDatabaseName("iX_Imagem_IdOfertaParceiro");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("iX_Imagem_usuarioId");

                    b.ToTable("Imagem", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("SubTitulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SubTitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Titulo");

                    b.HasKey("Id")
                        .HasName("pK_Notificacao");

                    b.ToTable("Notificacao", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.OfertaParceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Categoria");

                    b.Property<string>("CategoriaCupom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CategoriaCupom");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataCriacao");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Desconto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Descricao");

                    b.Property<Guid>("IdEndereco")
                        .HasColumnType("uuid")
                        .HasColumnName("IdEndereco");

                    b.Property<Guid>("IdParceiro")
                        .HasColumnType("uuid")
                        .HasColumnName("IdParceiro");

                    b.Property<Guid>("IdUsuarioCadastrante")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuarioCadastrante");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NomeProduto");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Preco");

                    b.Property<string>("QrCodePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("QrCodePath");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("Status");

                    b.Property<string>("TipoOferta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TipoOferta");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TipoProduto");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("Validade");

                    b.HasKey("Id")
                        .HasName("pK_OfertaParceiro");

                    b.HasIndex("IdEndereco")
                        .HasDatabaseName("iX_OfertaParceiro_IdEndereco");

                    b.HasIndex("IdParceiro")
                        .HasDatabaseName("iX_OfertaParceiro_IdParceiro");

                    b.ToTable("OfertaParceiro", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("Data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Status");

                    b.Property<string>("UrlPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UrlPagamento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id")
                        .HasName("pK_Pagamento");

                    b.ToTable("Pagamento", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Parceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contato");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataCriacao");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("idEmpresa");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pK_Parceiros");

                    b.HasIndex(new[] { "IdEmpresa" }, "IdEmpresa_Parceiro_Unique")
                        .IsUnique()
                        .HasDatabaseName("iX_Parceiros_idEmpresa");

                    b.HasIndex(new[] { "IdUsuario" }, "IdUsuario_Parceiro_Unique")
                        .IsUnique()
                        .HasDatabaseName("iX_Parceiros_idUsuario");

                    b.ToTable("Parceiros", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Titulo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("Valor");

                    b.HasKey("Id")
                        .HasName("pK_Plano");

                    b.ToTable("Plano", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text")
                        .HasColumnName("emailConfirmationToken");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailConfirmed");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Nome");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text")
                        .HasColumnName("resetPasswordToken");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resetPasswordTokenExpiry");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("Role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Senha");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("text")
                        .HasColumnName("UrlImagem");

                    b.HasKey("Id")
                        .HasName("pK_Usuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Assinatura", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Assinatura")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_Assinatura_Cliente");

                    b.HasOne("TamoJunto.Domain.Models.Pagamento", "IdPagamentoNavigation")
                        .WithOne("Assinatura")
                        .HasForeignKey("TamoJunto.Domain.Models.Assinatura", "IdPagamento")
                        .HasConstraintName("FK_Assinatura_Pagamento");

                    b.HasOne("TamoJunto.Domain.Models.Plano", "IdPlanoNavigation")
                        .WithMany()
                        .HasForeignKey("IdPlano")
                        .IsRequired()
                        .HasConstraintName("FK_Assinatura_Plano");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPagamentoNavigation");

                    b.Navigation("IdPlanoNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Backoffice", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("Backoffice")
                        .HasForeignKey("TamoJunto.Domain.Models.Backoffice", "IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Backoffice_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Cliente", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Empresa", "IdEmpresaNavigation")
                        .WithOne("Cliente")
                        .HasForeignKey("TamoJunto.Domain.Models.Cliente", "IdEmpresa")
                        .HasConstraintName("FK_Cliente_Empresa");

                    b.HasOne("TamoJunto.Domain.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("Cliente")
                        .HasForeignKey("TamoJunto.Domain.Models.Cliente", "IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Usuario");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.CupomCliente", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Cliente", "IdClienteNavigation")
                        .WithMany("CupomCliente")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_CupomCliente_Cliente");

                    b.HasOne("TamoJunto.Domain.Models.OfertaParceiro", "OfertaParceiro")
                        .WithOne("IdNavigation")
                        .HasForeignKey("TamoJunto.Domain.Models.CupomCliente", "IdOfertaParceiro")
                        .IsRequired()
                        .HasConstraintName("FK_CupomCliente_OfertaParceiro");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("OfertaParceiro");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Endereco", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Endereco")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Endereco_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.HistoricoCupom", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.CupomCliente", "IdCupomClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCupomClienteNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_HistoricoCupom_CupomCliente_idCupomClienteNavigationId");

                    b.HasOne("TamoJunto.Domain.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuarioNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_HistoricoCupom_Usuario_idUsuarioNavigationId");

                    b.Navigation("IdCupomClienteNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.HistoricoLogin", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_HistoricoLogin_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Imagem", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.OfertaParceiro", "IdOfertaParceiroNavigation")
                        .WithMany("Imagem")
                        .HasForeignKey("IdOfertaParceiro")
                        .HasConstraintName("FK_Imagem_OfertaParceiro");

                    b.HasOne("TamoJunto.Domain.Models.Usuario", "UsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_Imagem_Usuario");

                    b.Navigation("IdOfertaParceiroNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.OfertaParceiro", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Endereco", "IdEnderecoNavigation")
                        .WithMany("OfertaParceiro")
                        .HasForeignKey("IdEndereco")
                        .IsRequired()
                        .HasConstraintName("FK_OfertaParceiro_Endereco");

                    b.HasOne("TamoJunto.Domain.Models.Parceiro", "IdParceiroNavigation")
                        .WithMany("OfertaParceiro")
                        .HasForeignKey("IdParceiro")
                        .IsRequired()
                        .HasConstraintName("FK_OfertaParceiro_Parceiro");

                    b.Navigation("IdEnderecoNavigation");

                    b.Navigation("IdParceiroNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Parceiro", b =>
                {
                    b.HasOne("TamoJunto.Domain.Models.Empresa", "IdEmpresaNavigation")
                        .WithOne("Parceiro")
                        .HasForeignKey("TamoJunto.Domain.Models.Parceiro", "IdEmpresa")
                        .IsRequired()
                        .HasConstraintName("FK_Parceiro_Empresa");

                    b.HasOne("TamoJunto.Domain.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("Parceiro")
                        .HasForeignKey("TamoJunto.Domain.Models.Parceiro", "IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Parceiro_Usuario");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Cliente", b =>
                {
                    b.Navigation("Assinatura");

                    b.Navigation("CupomCliente");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Empresa", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Endereco", b =>
                {
                    b.Navigation("OfertaParceiro");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.OfertaParceiro", b =>
                {
                    b.Navigation("IdNavigation");

                    b.Navigation("Imagem");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Pagamento", b =>
                {
                    b.Navigation("Assinatura");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Parceiro", b =>
                {
                    b.Navigation("OfertaParceiro");
                });

            modelBuilder.Entity("TamoJunto.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Backoffice");

                    b.Navigation("Cliente");

                    b.Navigation("Endereco");

                    b.Navigation("Parceiro");
                });
#pragma warning restore 612, 618
        }
    }
}
