services:
  - type: web
    name: tamojunto-api
    env: dotnet
    plan: free
    buildCommand: dotnet publish TamoJunto.API/TamoJunto.API.csproj -c Release -o out
    startCommand: dotnet out/TamoJunto.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: https://0.0.0.0:8080 