<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="8.0.0" />
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Properties\**" />
      <Compile Remove="Program.cs" />
      <Compile Remove="TokenUtil.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Properties\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Properties\**" />
      <Content Remove="appsettings.json" />
      <Content Remove="appsettings.Development.json" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Properties\**" />
      <None Remove="TamoJunto.Infra.http" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TamoJunto.Domain\TamoJunto.Domain.csproj" />
    </ItemGroup>

</Project>
